# Generated by Django 5.1.3 on 2025-05-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='precio_aprx_unid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='tienda',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='turno',
            name='hora_inicio',
            field=models.TimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='acceso',
            unique_together={('usuario', 'dependiente')},
        ),
    ]
