# Generated by Django 5.1.3 on 2025-06-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_compra_precio_aprx_unid_alter_compra_tienda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependiente',
            name='medicamentos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
