# Generated by Django 5.1.3 on 2025-06-13 11:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependiente',
            name='foto_perfil',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
